### PR TITLE
Set $stateless default to false

### PR DESCRIPTION
**Pull request by stulogy**
Fixes #

## Changes proposed in this pull request:
-
-
-

In keeping with the laravel/socialite, and to allow user to specify whether they want to use stateless or not (using the `->stateless()` method), the default should be false.

### CODE REVIEW

**Comment by AndyWendt** [comment]
@stulogy Thanks for the PR!   We have found the default for the OAuth1 providers that we've tested to be stateless by default.  Do you have some example use cases that show that this would be a good idea to make the default?

**Comment by stulogy** [comment]
Well in that case you need to add a method so you can set the state, because right now the only method I could find was one to set the stateless bool to be true, which it is already by default. So, because of the cookie issue I’m experiencing, I want to make the connection to Trello to NOT be stateless, how do I do that?

**Comment by DraperStudio** [comment]
I have pushed https://github.com/SocialiteProviders/Manager/commit/3c2253b75b4a3056ae8369f532d045ab213ce063 so could you pull in the `dev-master` and test it?

**Comment by AndyWendt** [comment]
@DraperStudio made it so that you can call `->stateless(false)`

**Comment by stulogy** [comment]
How do I do that with composer? Right now I have this:

        "laravel/socialite": "^2.0",
        "socialiteproviders/slack": "^2.0",
        "socialiteproviders/asana": "^2.0",
        "socialiteproviders/trello": "^2.0”

**Comment by DraperStudio** [comment]
I've tagged `2.1.1` so just do `composer update`.

**Comment by stulogy** [comment]
Great – that works. Remember (for anyone else doing this), you need to run the `stateless(false)` method on both the redirect and after when you handle the callback.

**Comment by DraperStudio** [comment]
We will add details about that to the docs when we update them soon.

**Pull request closed without merging**
