### PR TITLE
emergency repair: guzzle config accept empty array not null.

### PR DESCRIPTION
**Pull request by sinkcup**
emergency repair #143

### CODE REVIEW

**Comment by m1guelpf** [comment]
I'm gonna merge this and tag so this is working, but please submit another PR with tests so this doesn't happen again :)

**Comment by sinkcup** [comment]
this problem come from https://github.com/SocialiteProviders/Manager/pull/138
@r-takky can you submit tests?

I received an report from @keesh7663 say:

>  tag v3.3.5 As an FYI, this completely breaks Discord Socialite login

so I emergency repair it, I don't know the reason. @m1guelpf

**Comment by rvanbaalen** [comment]
@sinkcup Can confirm that it also broke Basecamp (37signals provider) OAuth flow. Probably anything that used OAuth2.

Can also confirm that my flow works again now that I have updated to v3.3.6

**Comment by keesh7663** [comment]
also confirms that after installing the emergency patch the login flow works perfectly fine again (using Discord and Twitch providers)

**Pull request merged**
