### PR TITLE
Update for 5.4

### PR DESCRIPTION
**Pull request by lukepolo**
needs version bump

## Changes proposed in this pull request:
- Updates to Laravel 5.4 Support

### CODE REVIEW

**Comment by lukepolo** [comment]
Will need to wait till illuminate/contracts get released to 5.4

**Comment by tillkruss** [comment]
Just got released. Can you merge?

**Comment by lukepolo** [comment]
laravel/framework#17510

**Comment by tillkruss** [comment]
They have been tagged. Can you re-push or merge now?

**Comment by ahjorth** [comment]
+1 for this asap :)

**Comment by faustbrian** [comment]
Tagged `v3.0.0`

**Comment by tillkruss** [comment]
Thanks @faustbrian!

Could you tag the 3.0 release of `SocialiteProviders/Instagram`, or are we suppose to use the master?

**Comment by faustbrian** [comment]
There should now be a 5.4 release for every provider.

**Comment by ahjorth** [comment]
Thanks a lot @faustbrian, really appreciate your work :balloon:

**Pull request merged**
