### PR TITLE
Add "get user profile" from `token` and `secret` method

### PR DESCRIPTION
**Pull request by c00p3r**
Fixes #

## Changes proposed in this pull request:
Adding get `userFromTokenAndSecret` method to correspond changes already merged into main Socialite package here https://github.com/laravel/socialite/pull/193

oAuth2 has a method `userFromToken` but oAuth1 doesn't...
It's critical for apps working through API only.
Without it I can't work with Twitter API

### CODE REVIEW

**Comment by faustbrian** [comment]
Please add a test for this method.

**Comment by c00p3r** [comment]
@faustbrian I'm not sure I'll make right test for SocialiteProviders...
I don't see separate test for 'user()' method... to be an axample for me
Can u give me some tips?

**Comment by c00p3r** [comment]
I implemented this method manually for my app
And tested it manually
It works fine

**Comment by faustbrian** [comment]
Do you have an example of how you are using it in your app?

**Comment by c00p3r** [comment]
If you probably don't like my implementation than maybe you could do your own variant
Anyway we need the method that corresponds to Main Package's [method](https://github.com/laravel/socialite#retrieving-user-details-from-token) `userFromToken($token)`

**Comment by c00p3r** [comment]
My app accepts API requests with user token returned from Twitter API
 protected function getSocialAccountInfo($request)
    {
        switch ($this->socialDriver) {
            case 'instagram':
                return Socialite::driver($this->socialDriver)->stateless()->userFromToken($request->input('user_token'));
                break;
            case 'twitter':
                return Socialite::driver($this->socialDriver)->stateless()->userFromTokenAndSecret($request->input('user_token'), $request->input('user_token_secret'));
                break;
            default:
                return null;
        }
    }

**Comment by c00p3r** [comment]
Instagram uses oAuth2 and I have no problem using original `userFromToken`method
But unfortunately Twitter uses oAuth1... and for that case I have no method to retrieve user info from token

**Pull request merged**
