### PR TITLE
Add a coding standards GA to fix code with Laravel Pint.

### PR DESCRIPTION
**Pull request by lucasmichot**
This PR adds a coding standards GA to fix code with Laravel [Pint](https://laravel.com/docs/10.x/pint).

It also fixes the code to match those coding standards

### CODE REVIEW

**Comment by atymic** [comment]
See comments on other PR
https://github.com/SocialiteProviders/Providers/pull/1064#pullrequestreview-1597214663

**Comment by lucasmichot** [comment]
I have updated this PR @atymic 

I believe this the way it should work
the coding standard use the organization .github workflow: https://github.com/SocialiteProviders/.github/tree/main/.github/workflows

It creates a fix commit (if necessary) on push events :
see my initial commit: https://github.com/SocialiteProviders/Manager/pull/221/commits/0eb2e75caa551b2bf6c888d0c8414ea5de0d07cc
and the fix commit https://github.com/SocialiteProviders/Manager/pull/221/commits/26fa6cde3c7156059a5b231e4f4289995372db39

**Comment by atymic** [comment]
Will it run correctly for contributors as well?

**Comment by lucasmichot** [comment]
It should, my only concern is this :
https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs 

WDYT ?

**Comment by lucasmichot** [comment]
Introducing the PAT solve this.

This PR is ready to be reviewed @atymic

**Comment by atymic** [comment]
Sorry if i wasn't clear @lucasmichot, I meant just run the lint only (not fix) on the pull_request trigger, so we can know if theres issues

**Pull request closed without merging**
