### PR TITLE
Fix docblocks.

### PR DESCRIPTION
**Pull request by lucasmichot**
## Changes proposed in this pull request:
- Fix docblocks and add missing docblocks

### CODE REVIEW

**Comment by faustbrian** [comment]
DocBlocks should use the FQCN because otherwise they are not to helpful because you will still end up scrolling to the top of the file trying to find the FQCN of the class name you just read.

**Comment by lucasmichot** [comment]
But FQCN are mostly not set in this projects...
See \SocialiteProviders\Manager\Helpers\ConfigRetriever

**Comment by faustbrian** [comment]
All classes are referenced with `use` clauses at the top of the file. So if you see `ConfigInterface` with the DocBlocks at the moment you end up scrolling to the top of the file to find out that the interface can be found at `SocialiteProviders\Manager\Contracts\ConfigInterface`.

So a new and improved DocBlock should look the following to prevent having to go up to the top of the file.

```
/**
 * @var \SocialiteProviders\Manager\Contracts\ConfigInterface
 */
```

**Comment by lucasmichot** [comment]
ok

**Pull request closed without merging**
