### PR TITLE
Remove duplicate check.

### PR DESCRIPTION
**Pull request by lucasmichot**
## Changes proposed in this pull request:
- Remove duplicate check.

### CODE REVIEW

**Comment by faustbrian** [comment]
Please fix the `) ;` spacing issue. Also, you don't need to open and close a PR to just send the same again, you can commit multiple times to the same branch if there are any changes to be done.

**Comment by lucasmichot** [comment]
I thought StyleCI autofix was enabled

**Comment by faustbrian** [comment]
It is enabled, if it is not working it is an issue on StyleCIs end.

**Comment by faustbrian** [comment]
As I previously mentioned, please opening and closing PRs and then deleting the branches. Just commit the fix to the same branch instead of spamming PRs.

**Comment by lucasmichot** [comment]
Sorry for the spamming inconvenience

**Pull request closed without merging**
