### PR TITLE
[*] If the redirect option contains a relative path, it will automati…

### PR DESCRIPTION
**Pull request by suabahasa**
Fixes #

## Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by suabahasa** [comment]
I'm sorry I have no idea how to use test.

**Comment by faustbrian** [comment]
Will merge this once a test is added.

**Comment by mathieutu** [comment]
The problem here, is that the `setConfig` call overrides the work done in the `buildProvider` method. 
I will probably open an issue about that, because anyway, this is not a proper way of resolution.

**Comment by AndyWendt** [comment]
@suabahasa would you mind adding a test to this?  There's examples in the repo

**Comment by mathieutu** [comment]
@AndyWendt As I said, I think that this is not the good solution for that problem. 
In my opinion this issue is just a side effect of #115...

**Comment by xutl** [comment]
Great work

**Pull request closed without merging**
