### PR TITLE
Update AbstractProvider.php

### PR DESCRIPTION
**Pull request by daniel-james-lewis**
Fixes #

## Changes proposed in this pull request:
-
-
-

Some cookies get scrapped based on project cookie settings and project specific code. Changes stop errors in those circumstances.

### CODE REVIEW

**Comment by daniel-james-lewis** [comment]
for reference, issue #60 seems to confirm this.

**Comment by DraperStudio** [comment]
We need to use the `$_COOKIE` variable because we support both Laravel and Lumen. With your solution we ran into issues with Lumen and using the `$_COOKIE` variable fixed these issues.

**Comment by daniel-james-lewis** [comment]
I did have a look at the docs for Lumen and saw that 5.1 uses the same request model. What version of Lumen/Laravel are you supporting? This is still an issue for Laravel users, I'll look into it again and take Lumen into account.

**Comment by DraperStudio** [comment]
If you have tested it with Laravel and Lumen and can confirm that it works I can merge it.

**Comment by DraperStudio** [comment]
@daniel-james-lewis Any progress on this?

**Pull request merged**
