### PR TITLE
Update method call to existing method

### PR DESCRIPTION
**Pull request by ronnievisser**
Fixes #

## Changes proposed in this pull request:
- Fix undefined method SocialiteProviders\SalesForce\Provider::getAccessToken()

### CODE REVIEW

**Comment by faustbrian** [comment]
@bkuhl assured in the previous PR https://github.com/SocialiteProviders/Manager/pull/102 that this method call would be correct but now it apparently is wrong and has to be reverted? Could anyone please test any of these changes with an actual provider?

**Comment by bkuhl** [comment]
I did test this, in my local app with v3 of the providers.

@ronnievisser What version of the provider manager are you using?

**Comment by faustbrian** [comment]
@bkuhl I just checked myself and in 3.0 it is still called `getAccessTokenResponse ` and not `getAccessToken` like in the master branch which is not 3.0

**Comment by bkuhl** [comment]
Hrmm.... you're right... Sorry about that!  It seems I have a different problem...

**Comment by faustbrian** [comment]
@ronnievisser Thanks for the quick fix.

**Comment by ronnievisser** [comment]
Perfect! Now we can move on!

**Comment by ryzr** [comment]
This has broken other Socialite providers.

See https://github.com/mpociot/socialite-slack/blob/master/src/Provider.php

This extends `SocialiteProviders\Manager\OAuth2\AbstractProvider` but uses the method public `function getAccessToken($code)`

**Comment by faustbrian** [comment]
@ryzr This is not an official provider we from SocialiteProviders are offering so we don't offer support for that.

**Comment by ryzr** [comment]
Sorry about that, edited my comment above. Looks like the version constraint on their package needs to be adjusted.

Thanks for the fast response.

**Pull request merged**
