### PR TITLE
Request might not exist yet in testing env

### LINKED ISSUE #70: Session data I provide when testing gets ignored by Vkontakte provider
The issue is apparently not with this particular provider. If we inspect what happens when Facebook driver/provider is created, we can see that it's created, say, on demand. When `Socialite::driver('facebook')` is called in controller, it [follows][fb1] [this][fb2] [path][fb3].

With SocialiteProviders though, it [takes][sp1] the [other][sp2] [route][sp3]. With provider being created [in advance][sp4].

As a result, when I test routes that makes use of Vkontakte provider

```php
          return $this->withSession([
              'state' => '...',
          ])->get('/auth/vkontakte/callback?' . http_build_query([
              'state' => '...',
          ]));
```

provided state gets ignored. Workarounds are welcome.

P.S. I'm going to investigate it a little more...

[fb1]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Support/Manager.php#L87
[fb2]: https://github.com/laravel/socialite/blob/v2.0.20/src/SocialiteManager.php#L48-L50
[fb3]: https://github.com/laravel/socialite/blob/v2.0.20/src/SocialiteManager.php#L90-L93
[sp1]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Support/Manager.php#L85
[sp2]: https://github.com/laravel/framework/blob/v5.2.45/src/Illuminate/Support/Manager.php#L101
[sp3]: https://github.com/SocialiteProviders/Manager/blob/v2.1.9/src/SocialiteWasCalled.php#L52-L56
[sp4]: https://github.com/SocialiteProviders/Manager/blob/v2.1.9/src/SocialiteWasCalled.php#L48

### PR DESCRIPTION
**Pull request by x-yuri**
Fixes #70 

## Changes proposed in this pull request:
- create provider late, to make sure request has been created

### CODE REVIEW

**Comment by faustbrian** [comment]
Travis is now failing, please fix that before I merge it.

**Comment by x-yuri** [comment]
I get many more errors, even without my changes (tag: v2.2.1), can you explain that?

I'm running `php-7.1`, if anything.

```
FFF.....FF..EEEE.FF.........                                      28 / 28 (100%)

Time: 131 ms, Memory: 10.00MB

There were 4 errors:

1) SocialiteProviders\Manager\Test\OAuth2ProviderTest::it_allows_the_config_to_be_retrieved_from_the_services_array
BadMethodCallException: Method Mockery_5_SocialiteProviders_Manager_Test_Stubs_OAuth2ProviderStub::setConfig() does not exist on this mock object

/home/yuri/prj/Manager/src/SocialiteWasCalled.php:131
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:84
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:56
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:80
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Matcher/Closure.php:35
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Expectation.php:357
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Expectation.php:318
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:173
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:138
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:91
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:98

2) SocialiteProviders\Manager\Test\OAuth2ProviderTest::it_allows_a_custom_config_to_be_passed_dynamically
Error: Call to undefined method SocialiteProviders\Manager\Test\Stubs\OAuth2ProviderStub::config()

/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:108

3) SocialiteProviders\Manager\Test\OAuth2ProviderTest::it_retrieves_from_the_config_if_no_config_is_provided
BadMethodCallException: Method Mockery_5_SocialiteProviders_Manager_Test_Stubs_OAuth2ProviderStub::setConfig() does not exist on this mock object

/home/yuri/prj/Manager/src/SocialiteWasCalled.php:131
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:84
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:56
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:128
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Matcher/Closure.php:35
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Expectation.php:357
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Expectation.php:318
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:173
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:138
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:91
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:140

4) SocialiteProviders\Manager\Test\OAuth2ProviderTest::it_should_build_a_provider_and_extend_socialite
BadMethodCallException: Method Mockery_5_SocialiteProviders_Manager_Test_Stubs_OAuth2ProviderStub::setConfig() does not exist on this mock object

/home/yuri/prj/Manager/src/SocialiteWasCalled.php:131
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:84
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:56
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:158
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Matcher/Closure.php:35
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Expectation.php:357
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/Expectation.php:318
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:173
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:138
/home/yuri/prj/Manager/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:91
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:177

--

There were 7 failures:

1) SocialiteProviders\Manager\Test\ConfigRetrieverTest::it_throws_if_there_is_a_problem_with_the_env_config
Failed asserting that exception of type "Error" matches expected exception "\SocialiteProviders\Manager\Exception\MissingConfigException". Message was: "Call to undefined function SocialiteProviders\Manager\Helpers\app()" at
/home/yuri/prj/Manager/src/Helpers/ConfigRetriever.php:155
/home/yuri/prj/Manager/src/Helpers/ConfigRetriever.php:47
/home/yuri/prj/Manager/tests/ConfigRetrieverTest.php:22
.

2) SocialiteProviders\Manager\Test\ConfigRetrieverTest::it_throws_if_there_is_a_problem_with_the_services_config
Failed asserting that exception of type "Error" matches expected exception "\SocialiteProviders\Manager\Exception\MissingConfigException". Message was: "Call to undefined function SocialiteProviders\Manager\Helpers\app()" at
/home/yuri/prj/Manager/src/Helpers/ConfigRetriever.php:181
/home/yuri/prj/Manager/src/Helpers/ConfigRetriever.php:66
/home/yuri/prj/Manager/tests/ConfigRetrieverTest.php:35
.

3) SocialiteProviders\Manager\Test\ConfigRetrieverTest::it_throws_if_there_are_missing_items_in_the_services_config
Failed asserting that exception of type "Error" matches expected exception "\SocialiteProviders\Manager\Exception\MissingConfigException". Message was: "Call to undefined function SocialiteProviders\Manager\Helpers\app()" at
/home/yuri/prj/Manager/src/Helpers/ConfigRetriever.php:181
/home/yuri/prj/Manager/src/Helpers/ConfigRetriever.php:66
/home/yuri/prj/Manager/tests/ConfigRetrieverTest.php:48
.

4) SocialiteProviders\Manager\Test\OAuth1ProviderTest::it_throws_if_given_an_invalid_oauth1_provider
Failed asserting that exception of type "BadMethodCallException" matches expected exception "SocialiteProviders\Manager\Exception\InvalidArgumentException". Message was: "Method Mockery_1_Laravel_Socialite_SocialiteManager::extend() does not exist on this mock object" at
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth1ProviderTest.php:66
.

5) SocialiteProviders\Manager\Test\OAuth1ProviderTest::it_throws_if_given_an_invalid_oauth1_server
Failed asserting that exception of type "BadMethodCallException" matches expected exception "SocialiteProviders\Manager\Exception\InvalidArgumentException". Message was: "Method Mockery_1_Laravel_Socialite_SocialiteManager::extend() does not exist on this mock object" at
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth1ProviderTest.php:84
.

6) SocialiteProviders\Manager\Test\OAuth2ProviderTest::it_throws_if_given_an_invalid_oauth2_provider
Failed asserting that exception of type "BadMethodCallException" matches expected exception "SocialiteProviders\Manager\Exception\InvalidArgumentException". Message was: "Method Mockery_1_Laravel_Socialite_SocialiteManager::extend() does not exist on this mock object" at
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:233
.

7) SocialiteProviders\Manager\Test\OAuth2ProviderTest::it_throws_if_oauth1_server_is_passed_for_oauth2
Failed asserting that exception of type "BadMethodCallException" matches expected exception "SocialiteProviders\Manager\Exception\InvalidArgumentException". Message was: "Method Mockery_1_Laravel_Socialite_SocialiteManager::extend() does not exist on this mock object" at
/home/yuri/prj/Manager/src/SocialiteWasCalled.php:62
/home/yuri/prj/Manager/tests/OAuth2ProviderTest.php:253
.

ERRORS!
Tests: 28, Assertions: 35, Errors: 4, Failures: 7.
```

**Comment by faustbrian** [comment]
If I run the tests on my local machine without your changes all tests pass on the latest release, as soon as I add your changes a bunch of errors pop up.

**Comment by x-yuri** [comment]
Sorry, it takes so long. I don't have much time, but still I wanted to find out why I have extra tests failing.

From what I can see, Travis (or probably GitHub) first merges my PR into `master` and only then [Travis] runs tests. Correct me if I'm wrong. That might explain why I have more tests failing. I ran the tests being at my branch (no pulling changes from your repo and rebasing my changes onto `master`).

But I just pulled changes from your repo and tried to run tests being at f57877e (v3.0.4), and I still have one test failing. I'll try to look into it now.

**Comment by x-yuri** [comment]
@faustbrian check if it's okay

**Pull request merged**
